### ISSUE TITLE
not work in multiple form

### ISSUE THREAD

**Issue by ericfpavoni** [BKcore/NoCSRF#4]
Hi, Thanks for great class.

i have two form in my page. when i  generate nocsrf i see one token for two form and after submit always i see error and my form not submitted. how to work your class for multiple form in page.

thanks for time

best regards

**Comment by JBlond** [comment]
It has that option in the check() function $multiple
see https://github.com/BKcore/NoCSRF/blob/master/example/nocsrf.php line 24  and line 28
